assert_capture.py, assert_capture.FP_assert_true_with_id_not_captured_ok, 1, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
assert_capture.py, assert_capture.assert_false_with_id_not_captured_bad, 1, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
assert_capture.py, assert_capture.assert_false_with_id_captured_bad, 1, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
assert_capture.py, assert_capture.FP_assert_true_with_id_skipped_ok, 1, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
assert_capture.py, assert_capture.assert_false_with_id_skipped_bad, 1, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
assert_level0.py, assert_level0.assert_true_bad, 1, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
assert_level0.py, assert_level0.run_assert_latent_bad, 1, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
assert_oo_basic.py, assert_oo_basic.get_attr_after_init_bad, 2, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
assert_oo_basic.py, assert_oo_basic.get_attr_after_set_bad, 3, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
assert_oo_single_inheritance.py, assert_oo_single_inheritance.not_inherited_attribute_bad, 3, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
assert_oo_single_inheritance.py, assert_oo_single_inheritance.not_inherited_method_bad, 3, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
assert_oo_single_inheritance.py, assert_oo_single_inheritance.inherited_class_attribute_B_bad, 2, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
assert_oo_single_inheritance.py, assert_oo_single_inheritance.inherited_class_attribute_A_bad, 2, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
assert_oo_single_inheritance.py, assert_oo_single_inheritance.inherited_method_bad, 3, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
assert_oo_single_inheritance.py, assert_oo_single_inheritance.inherited_class_modified_attribute_B_1_bad, 3, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
assert_oo_single_inheritance.py, assert_oo_single_inheritance.inherited_class_modified_attribute_B_2_bad, 3, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
assert_oo_single_inheritance.py, assert_oo_single_inheritance.FP_inherited_class_modified_attribute_A_1_ok, 3, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
assert_oo_single_inheritance.py, assert_oo_single_inheritance.FP_inherited_class_modified_attribute_A_2_ok, 3, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
async_dict.py, async_dict.str_key_access_bad, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_global.py, async_global.__module_body__, 23, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,parameter `globals` of async_global.__module_body__,assigned,when calling `Closure[async_global.set_unwaited_global].call` here,parameter `__this` of Closure[async_global.set_unwaited_global].call,when calling `async_global.set_unwaited_global` here,allocated by async call here,awaitable becomes unreachable here]
async_import_simple.py, async_import_simple.with_import_bad, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_import_simple.py, async_import_simple.with_from_import_bad, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_import_simple.py, async_import_simple.with_imported_class_bad, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_import_with_package.py, async_import_with_package.bad1, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_import_with_package.py, async_import_with_package.bad2, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_import_with_package.py, async_import_with_package.bad3, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_import_with_package.py, async_import_with_package.from_class_bad3, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_import_with_package.py, async_import_with_package.bad5, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_import_with_package.py, async_import_with_package.bad6, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_lambda.py, async_lambda.lambda_bad, 2, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,when calling `Closure[async_lambda.lambda_bad._$lambda].call` here,when calling `async_lambda.lambda_bad::_$lambda` here,allocated by async call here,awaitable becomes unreachable here]
async_lambda.py, async_lambda.lambda_param_bad, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,when calling `Closure[async_lambda._$lambda].call` here,when calling `async_lambda._$lambda` here,allocated by async call here,awaitable becomes unreachable here]
async_lambda.py, async_lambda.lambda_param_bad, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,when calling `Closure[async_lambda.lambda_param_bad_call_bad._$lambda].call` here,when calling `async_lambda.lambda_param_bad_call_bad::_$lambda` here,allocated by async call here,awaitable becomes unreachable here]
async_lambda.py, async_lambda.lambda_param_bad_call_bad, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_lambda.py, async_lambda.__module_body__, 30, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_level0.py, async_level0.sleep_bad, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_level0.py, async_level0.call_sleep_bad, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_level0.py, async_level0.call_sleep_with_branchs_bad1, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_level0.py, async_level0.call_sleep_with_branchs_bad2, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_level0.py, async_level0.tuple0_bad, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_level0.py, async_level0.tuple1_bad, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_level0.py, async_level0.with_str_bad, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_level0.py, async_level0.call_fst_bad, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_level0.py, async_level0.compare_lt_bad, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_level0.py, async_level0.compare_gt_bad, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_level0.py, async_level0.use_py_bool_bad, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_level0.py, async_level0.use_py_get_iter_bad, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_level0.py, async_level0.call_get_option_awaitable_eq_test_none_bad, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,when calling `Closure[async_level0.get_option_awaitable].call` here,when calling `async_level0.get_option_awaitable` here,allocated by async call here,awaitable becomes unreachable here]
async_level1.py, async_level1.D::main, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_level1.py, async_level1.instantiate_D_bad, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,when calling `Closure[async_level1.D.__init__].call` here,when calling `async_level1.D::__init__` here,allocated by async call here,awaitable becomes unreachable here]
async_typing.py, async_typing.await_condition_typing_int_bad, 4, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_typing.py, async_typing.await_condition_typing_with_arg_bad, 4, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_typing.py, async_typing.fp_await_condition_typing_user_defined_ok, 5, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_typing.py, async_typing.fp_await_condition_typing_fun_ok, 7, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_typing.py, async_typing.await_condition_is_none_bad, 3, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_typing.py, async_typing.await_condition_bool_none_bad, 5, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_typing.py, async_typing.fp_await_condition_val_equal_ok, 6, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
async_typing.py, async_typing.await_condition_phys_equal_bad, 6, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
builtins.py, builtins.fp_dict_comp_ok, 1, PULSE_UNAWAITED_AWAITABLE, no_bucket, ERROR, [allocation part of the trace starts here,allocated by async call here,awaitable becomes unreachable here]
cyclic_import.py, cyclic_import.__module_body__, 5, MUTUAL_RECURSION_CYCLE, no_bucket, WARNING, [`cyclic_import.__module_body__` makes a recursive call to `cyclic_import.__module_body__`]
demo_basic_oo/demo0.py, demo_basic_oo::demo0.assert_bad, 1, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
demo_basic_oo/demo1.py, demo_basic_oo::demo1.a_cow_can_not_quack_bad, 2, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
demo_basic_oo/demo2.py, demo_basic_oo::demo2.a_cow_can_not_quack_bad, 2, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
demo_basic_oo/demo3.py, demo_basic_oo::demo3.a_cow_can_not_quack_bad, 2, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
demo_basic_oo/demo4.py, demo_basic_oo::demo4.a_cow_can_not_quack_bad, 2, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
demo_basic_oo/demo5.py, demo_basic_oo::demo5.FP_a_duck_can_quack_ok, 2, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
demo_basic_oo/demo5.py, demo_basic_oo::demo5.a_cow_can_not_quack_bad, 2, PULSE_ASSERTION_ERROR, no_bucket, ERROR, []
dict_import.py, dict_import.read_class_companion_property_with_import_bad, 2, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_import.py, dict_import.instance_attribute_from_class_companion_with_import_bad, 3, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_import.py, dict_import.instance_attribute_with_import_bad, 3, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_import.py, dict_import.read_class_companion_property_with_import_from_bad, 2, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_import.py, dict_import.instance_attribute_from_class_companion_with_import_from_bad, 3, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_import.py, dict_import.instance_attribute_with_import_from_bad, 3, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_level0.py, dict_level0.dict_missing_key_const_str_bad, 2, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_level0.py, dict_level0.dict_size1_missing_key_const_str_bad, 2, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_level0.py, dict_level0.dict_missing_key_const_str_with_int_key_bad, 2, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_level0.py, dict_level0.dict_missing_key_const_str_store_int_key_bad, 3, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_level0.py, dict_level0.dict_access_fun_call_bad, 2, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [in call to `Closure[dict_level0.get_dict].call`,in call to `dict_level0.get_dict`,allocated by call to `new` (modelled),returned,return from call to `dict_level0.get_dict`,returned,return from call to `Closure[dict_level0.get_dict].call`,read to uninitialized value occurs here]
dict_level0.py, dict_level0.dict_missing_key_dict_builtin_const_map_bad, 2, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_level0.py, dict_level0.dict_missing_key_builtin_empty_bad, 2, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_level0.py, dict_level0.dict_missing_str_key_in_op_bad, 3, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_level0.py, dict_level0.fp_dict_missing_int_key_in_op_ok, 3, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_level0.py, dict_level0.fp_test_dict_kwargs_ok, 6, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_level0.py, dict_level0.fp_with_exec_ok, 4, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_object_oriented.py, dict_object_oriented.set_attribute_with_init_bad, 3, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_object_oriented.py, dict_object_oriented.set_attribute_with_init_read_with_getter_bad, 3, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_object_oriented.py, dict_object_oriented.set_attribute_with_setter_read_with_getter_bad, 4, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_object_oriented.py, dict_object_oriented.set_attribute_with_init_read_with_return_get_key_bad, 3, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_object_oriented.py, dict_object_oriented.read_class_companion_property_bad, 2, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_object_oriented.py, dict_object_oriented.instance_attribute_from_class_companion_bad, 3, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_object_oriented.py, dict_object_oriented.instance_attribute_bad, 3, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
dict_object_oriented.py, dict_object_oriented.DictField::get_key_bad, 2, PULSE_DICT_MISSING_KEY, no_bucket, ERROR, [allocated by call to `new` (modelled),read to uninitialized value occurs here]
